
services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    environment:
      - OLLAMA_URL=http://ollama_server:8001 
    depends_on:
      - ollama
    networks:
      - app_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "8001:8001"  
    environment:
      - MODEL=llama3.2:1b  
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
